### PR TITLE
Bash parser now parses expansions and the simplifier simplifies them

### LINKED ISSUE #328: Dependency package not correctly parsed
How to reproduce:

``` shell
$ sudo aura -A retroshare
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `qt4[@]}[@]}[@]}` could not be found. You may need to search for a package to satisfy it.
```

However, the PKGBUILD of the package mentions `qt4` (https://aur.archlinux.org/packages/re/retroshare/PKGBUILD) but not the weird output Auras complains about.

### PR DESCRIPTION
**Pull request by theotherjimmy**
Should fix #328

### CODE REVIEW

File: src/Bash/Base.hs [hunk 1]
```diff
@@ -74,15 +77,24 @@ toNamespace (_:fs) = toNamespace fs
...
+  Nothing -> Nothing
+  Just bs -> Just $ foldr (++) [] $ map fromBashString bs
+
+fromBashString :: BashString -> [String]
+fromBashString (SingleQ s) = [s]
+fromBashString (DoubleQ l) = fromBashStringList l
+fromBashString (NoQuote l) = fromBashStringList l
+fromBashString (Backtic c) = ['`' : unwords (fromCommand c) ++ "`"]
+
+fromBashStringList :: [Either BashExpansion String] -> [String]
```
Comment (fosskers) [inline src/Bash/Base.hs]:
```
fromBashStringList :: [Either BashExpansion String] -> [String]
fromBashStringList = rights
```
This would do the job.

Comment (theotherjimmy) [inline src/Bash/Base.hs]: Thanks! I'll update my PR.

Comment (fosskers) [inline src/Bash/Base.hs]: You can probably just get rid of that function altogether, and just call `rights` directly.

Comment (theotherjimmy) [inline src/Bash/Base.hs]: I did :] thanks.

File: src/Bash/Base.hs [hunk 2]
```diff
@@ -74,15 +78,15 @@ toNamespace (_:fs) = toNamespace fs
 -- | Never call this directly. Use `value` in `Aura/Bash`.
 getVar :: Namespace -> String -> Maybe [String]
 getVar ns s = case M.lookup s ns of
-                Nothing -> Nothing
-                Just bs -> Just $ map fromBashString bs
+  Nothing -> Nothing
+  Just bs -> Just $ foldr (++) [] $ map fromBashString bs
```
Comment (bb010g) [inline src/Bash/Base.hs]: `foldr (++) []` can just be `map fold`. (Also, @fosskers, what's aura style with regards to fmap vs. map?)

File: src/Bash/Base.hs [hunk 3]
```diff
@@ -74,15 +78,15 @@ toNamespace (_:fs) = toNamespace fs
...
+fromBashString :: BashString -> [String]
+fromBashString (SingleQ s) = [s]
+fromBashString (DoubleQ l) = rights l
+fromBashString (NoQuote l) = rights l
+fromBashString (Backtic c) = ['`' : unwords (fromCommand c) ++ "`"]
 
-fromCommand :: Field -> String
-fromCommand (Command c as) = unwords $ c : map fromBashString as
+fromCommand :: Field -> [String]
+fromCommand (Command c as) =  [c] ++ foldr (++) [] (map fromBashString as)
```
Comment (bb010g) [inline src/Bash/Base.hs]: `[c] ++ map fold (map fromBashString as) === c : map (fold . fromBashString) as`

File: src/Bash/Simplify.hs [hunk 4]
```diff
@@ -74,18 +74,50 @@ replace' somethingElse = return somethingElse
 
 replaceStr :: BashString -> State Namespace BashString
 replaceStr s@(SingleQ _) = return s
-replaceStr (DoubleQ s)   = DoubleQ `fmap` replaceStr' s
-replaceStr (NoQuote s)   = NoQuote `fmap` replaceStr' s
+replaceStr (DoubleQ s)   = expandStr s >>= \strs -> return $ DoubleQ $ map Right strs
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `expandStr s >>= (return . DoubleQ . map Right)`
Another style question, @fosskers: `return` or `pure`? I'd imagine `pure` due to AMP.

File: src/Bash/Simplify.hs [hunk 5]
```diff
@@ -74,18 +74,50 @@ replace' somethingElse = return somethingElse
...
+  lhs <- expandStr' x
+  rhs <- expandStr xs
+  return $ lhs ++ rhs
+
+expandStr' :: Either BashExpansion String -> State Namespace [String]
+expandStr' (Right s) = return [s]
+expandStr' (Left (BashExpansion var sub)) = do
+  subscript <- mapM expandWrapper sub
+  ns <- get
+  getIndexedString ns var $ foldr (++) "" subscript
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `foldr (++) "" subscript === fold subscript`

File: src/Bash/Simplify.hs [hunk 6]
```diff
@@ -74,18 +74,50 @@ replace' somethingElse = return somethingElse
...
+  Nothing -> return []
+  Just bstrs -> getIndexedString' bstrs idx
+
+getIndexedString' :: [BashString] -> String -> State Namespace [String]
+getIndexedString' bstrs "" = do
+  singlestr <- replaceStr $ head bstrs
+  return $ fromBashString singlestr
+getIndexedString' bstrs "*" = do
+  strings <- mapM replaceStr bstrs
+  return $ foldr (++) [] $ map fromBashString strings
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `return $ map (fold . fromBashString) strings`

File: src/Bash/Simplify.hs [hunk 7]
```diff
@@ -74,18 +74,50 @@ replace' somethingElse = return somethingElse
...
+getIndexedString' bstrs "@" = getIndexedString' bstrs "*"
+getIndexedString' bstrs num = do
+  singlestr <- replaceStr $ bstrs !! read num
+  return $ fromBashString singlestr
+
+expandWrapper :: BashString -> State Namespace String
+expandWrapper (SingleQ s) = return s
+expandWrapper (DoubleQ s) = do
+  strs <- expandStr s
+  return $ foldr (++) "" strs
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `return $ fold strs`

File: src/Bash/Simplify.hs [hunk 8]
```diff
@@ -74,18 +74,50 @@ replace' somethingElse = return somethingElse
...
+expandWrapper (NoQuote s) = do
+  strs <- expandStr s
+  return $ foldr (++) "" strs
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `return $ fold strs`

File: src/Bash/Simplify.hs [hunk 9]
```diff
@@ -74,18 +74,50 @@ replace' somethingElse = return somethingElse
...
+expandWrapper (Backtic f) = replace' f >>= \x -> return $ unwords $ fromCommand x
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `replace' f >>= (return . unwords . fromCommand)`

**Comment by bb010g** [comment]
Related to parsing, do we want to switch over to [Megaparsec](https://hackage.haskell.org/package/megaparsec) ([rationale](https://notehub.org/w7037)).

File: src/Bash/Simplify.hs (hunk 6 above)
Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: I'm 60% sure that should be fold $ map fromBashString strings. Otherwise
you concatenate expanded bash arrays into one element of the bigger array
instead of extending it by the contents of the expanding variable (the
primary use case for this part of bash by my non-scientific survey).

Comment (bb010g) [inline src/Bash/Simplify.hs]: Sorry. `concatMap`?

File: src/Bash/Simplify.hs (hunk 9 above)
Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: A good number of the do-style blocks can be reduced to this style. All
cases of expandWrapper and getIndexedString in fact. They are much cleaner.
I will be updating the PR when I wake up tomorrow.

Comment (bb010g) [inline src/Bash/Simplify.hs]: If you want to do style adjustments outside of the scope of parsing bash expansions, please make a new PR.

File: src/Bash/Simplify.hs (hunk 6 above)
Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: Yup. Replaced all instances. The code is looking much better. Thanks.

File: src/Bash/Simplify.hs (hunk 9 above)
Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: I'll undo that. It slipped by me.

Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: Actually, I'm now confused. Do you mean the style suggestions you were
making or just the indentation things that I missed? Both?

Comment (bb010g) [inline src/Bash/Simplify.hs]: I meant for the project as a whole. I thought you were thinking of going through *everything*. Sorry. :) A separate PR would work better there because it's a separate discussion. I'm not quite sure what general aura policy on when you switch to do-notation is, and I'm currently on mobile and not able to check. I think it would be worth a discussion, however. What you may want to do is just use do-notation for now and then PR the style change with this as a sample. As for indentation problems, fixes are always good.

Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: Ah. I'm just intent on tidying up my current pull request. I'm only
changing the functions that I made/modified. Nothing so broad. I'll also
take a look (I'm also on mobile), though with the revisions, there is much
less use of do notation. I will make the do to no-do revisions as a sperate
PR, with a discussion on style there as you recommended.

File: src/Bash/Base.hs (hunk 2 above)
Comment (fosskers) [inline src/Bash/Base.hs]: `map` is one less character and should always be used for lists.

File: src/Bash/Simplify.hs (hunk 4 above)
Comment (fosskers) [inline src/Bash/Simplify.hs]: `pure`, given that `return` is likely to be removed soon.

**Comment by fosskers** [comment]
@bb010g I like it. I'll start by switching my [new version number library](https://github.com/fosskers/haskell-versions) to it to try it out.

**Comment by bb010g** [comment]
@fosskers On map vs. fmap: The extra character doesn't make a noticeable difference. It's one character, and we have the room. I'd be more prone to use it because of the same reason FTP happened: the type better describes what is needed for the function to work, and it will just keep working if we change data structures. Haskell is not normally about constricting usage where it doesn't need to be constricted.

**Comment by fosskers** [comment]
`Text` only with Aura2. I agree that `fmap` does make it clear that "I'm operating on a Functor now" instead of being constrained to the idea of Lists.

**Comment by fosskers** [comment]
Hey @theotherjimmy , if you make the other style changes as noted in the comments, I will merge this in.

File: src/Bash/Simplify.hs (hunk 9 above)
Comment (bb010g) [inline src/Bash/Simplify.hs]: This can actually just be refactored to `expandWrapper (Backtic f) = unwords . fromCommand <$> replace' f` via `replace' f >>= (return . unwords . fromCommand)` and the monad laws.

**Comment by theotherjimmy** [comment]
I have been working on another branch to do the cleanup. I will merge it (it's a fast-forward I think).

File: src/Bash/Simplify.hs (hunk 9 above)
Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: That is not the only instance. Commits comming soon.

**Comment by theotherjimmy** [comment]
Sorry for a huge pile of commits. They should all correspond to a single style suggestion applied across all of the code I added.

**Comment by bb010g** [comment]
Just squash them.

**Comment by bb010g** [comment]
`mapM` -> `traverse` and `map` -> `fmap`, then LGTM. (`<$>` is used everywhere and it's just `fmap` under the hood.)

**Comment by theotherjimmy** [comment]
I'll add that commit and squash (will rewrite history).

**Comment by theotherjimmy** [comment]
`map` -> `fmap` in the parser or simplifier or both?

**Comment by bb010g** [comment]
Both.

**Comment by theotherjimmy** [comment]
good catch. Updated.

File: src/Bash/Parser.hs [hunk 10]
```diff
@@ -123,10 +137,10 @@ unQuoted = map NoQuote <$> extrapolated []
 -- will not be expanded and will retain their braces.
 extrapolated :: [Char] -> Parser [String]
 extrapolated stops = do
-  xs <- plain <|> bracePair
+  xs <- plain <|>  bracePair
   ys <- option [""] $ try (extrapolated stops)
   return [ x ++ y | x <- xs, y <- ys ]
-      where plain = (: []) `fmap` many1 (noneOf $ " \n{}()" ++ stops)
+      where plain = (: []) `fmap` many1 (noneOf $ " $\n{}[]()" ++ stops)
```
Comment (bb010g) [inline src/Bash/Parser.hs]: `fmap` > `<$>`

File: src/Bash/Simplify.hs [hunk 11]
```diff
@@ -93,7 +113,7 @@ replaceIf i@(If comp fs el) = do
   let (op, l, r) = deComp comp
   left  <- fromBashString `fmap` replaceStr l
   right <- fromBashString `fmap` replaceStr r
```
Comment (bb010g) [inline src/Bash/Simplify.hs]: `<$>`

Comment (theotherjimmy) [inline src/Bash/Simplify.hs]: I did not touch these lines. Is this really appropliate for this PR?

Comment (bb010g) [inline src/Bash/Simplify.hs]: Oh, sorry. *derp*
I'll put in a separate PR for those.

**Comment by fosskers** [comment]
This works.

**Comment by fosskers** [comment]
Thanks for this.
